"""
Lesson 6 / ingestion - Crawl python.langchain.com and index it into Pinecone.

Production-shaped ingestion pipeline:
    CRAWL   TavilyCrawl over the docs site      -> raw markdown per page
    WRAP    each page                           -> Document(+ source URL metadata)
    SPLIT   RecursiveCharacterTextSplitter      -> 4000-char chunks, 200 overlap
    INDEX   asyncio.gather over batches of 500  -> concurrent upserts to Pinecone

Long-running and paid (crawling + embedding thousands of chunks). Run once.
Python puts this file's own directory on sys.path[0], so the sibling `logger`
import resolves from any working directory:
    uv run python app/ingestion.py
"""

import asyncio
import hashlib
import json
import os
import re
import ssl
from pathlib import Path
from typing import Any, Dict, List, Optional


import certifi
import httpx
from dotenv import load_dotenv

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings
from langchain_pinecone import PineconeVectorStore
from langchain_tavily import TavilyCrawl, TavilyExtract, TavilyMap

# Sibling module, imported absolutely -> this file must be run from its own
# folder (or that folder must be on PYTHONPATH).
from logger import (
    Colors, log_info,
    log_success, log_warning,
    log_error, log_header
)

# Project root (this file lives in app/), used both for the local chunk dump
# that core.py reads for BM25 and to keep the path stable regardless of cwd.
DATA_DIR = Path(__file__).resolve().parent.parent / "data"
CHUNKS_PATH = DATA_DIR / "chunks.json"

# Strudel's richest documentation (hundreds of functions: lpf, gain, euclid...)
# is NOT a crawlable web page - it's the "reference" tab inside the REPL
# (strudel.cc), rendered client-side from data baked into the JS bundle at
# build time. That data is generated by the `jsdoc` CLI (see jsdoc/jsdoc.config.json
# and the "jsdoc-json" script in the repo's package.json) from JSDoc comments
# directly above each function in packages/**/*.mjs. Pulling the source and
# re-parsing those comments is the only way to get this content into the RAG.
STRUDEL_REPO = "uzu/strudel"
STRUDEL_BRANCH = "main"
CODEBERG_API_BASE = "https://codeberg.org/api/v1"
CODEBERG_RAW_BASE = f"https://codeberg.org/{STRUDEL_REPO}/raw/branch/{STRUDEL_BRANCH}/"
CODEBERG_SRC_BASE = f"https://codeberg.org/{STRUDEL_REPO}/src/branch/{STRUDEL_BRANCH}/"
REFERENCE_SOURCE_EXTENSIONS = (".mjs", ".js", ".jsx")

# One JSDoc comment block: leading free-text description, then @tag lines.
# @example can repeat; each repetition's body runs until the next @tag or the
# end of the comment.
_JSDOC_BLOCK_RE = re.compile(r"/\*\*(.*?)\*/", re.DOTALL)
_JSDOC_TAG_LINE_RE = re.compile(r"^@(\w+)\s*(.*)$")

load_dotenv()  # Load environment variables from .env file


# macOS ships a Python without the system trust store wired up, so crawling
# HTTPS pages fails with SSLCertVerificationError. Pointing both requests and
# the stdlib at certifi's CA bundle fixes it for every library in the process.
# Configure SSL context to use certifi certificates
ssl_context = ssl.create_default_context(cafile=certifi.where())
os.environ["SSL_CERT_FILE"] = certifi.where()
os.environ["REQUESTS_CA_BUNDLE"] = certifi.where()


# text-embedding-3-small: 1536 dims, ~5x cheaper than ada-002 and better on
# retrieval benchmarks. The Pinecone index must be created with dimension 1536.
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small",
    show_progress_bar=True,
    chunk_size=50,   # texts per embedding HTTP request (batching, not text length)
    retry_min_seconds=10 # removing it the error 429 appears, so we set it to 10 seconds to avoid hitting the rate limit too quickly.
)

vectorStore = PineconeVectorStore(index_name="strudel-doc-index", embedding=embeddings)

'''
The difference between Chroma and Pinecone is that Chroma is a local vector store that stores embeddings on disk,
while Pinecone is a managed vector database service that provides scalable and efficient storage and retrieval of embeddings in the cloud.
'''

# Three complementary Tavily tools:
#   TavilyExtract - pull clean text out of a KNOWN list of URLs
#   TavilyMap     - discover the URL graph of a site without downloading content
#   TavilyCrawl   - discover AND extract in one call (what main() actually uses)
tavily_extract = TavilyExtract()
tavily_map = TavilyMap(max_depth=5, max_breath=20, max_pages=1000)
tavily_crawl = TavilyCrawl()



async def main():
    """Main async function to orchestrate the entire process."""
    log_header("DOCUMENTATION INGESTION PIPELINE")

    log_info(
        "TavilyCrawl: Starting to Crawl dicumentation from https://strudel.cc/workshop/getting-started/", 
        color=Colors.PURPLE
    )

    # One call fans out over the whole docs site and returns extracted content.
    # Crawl the documentation site.
    # strudel.cc's left sidebar nav (workshop/learn/recipes) is rendered on
    # every page, so all doc pages are reachable within 1-2 hops from
    # getting-started; max_depth=20 was massively overkill for that reason.
    # select_paths/exclude_paths are deterministic path filters (checked
    # against the site's real nav: /workshop/*, /learn/*, /recipes/* are the
    # actual doc sections; /blog/*, /intro/showcase* and /de/* are blog posts,
    # a community showcase, and a duplicate German translation - all noise
    # for a documentation RAG corpus). "instructions" is only a soft semantic
    # hint on top of that, not a hard filter, so it's kept short and specific
    # rather than the previous "content strudel documentation" (a keyword
    # jumble, not an actual instruction).
    res = tavily_crawl.invoke({
        "url": "https://strudel.cc/workshop/getting-started/", # the URL of the documentation site to crawl
        "max_depth": 3, # nav is on every page, so 1-2 hops covers the whole site; kept a small buffer
        "extract_depth": "advanced", # treat more data as relevant for extraction, including code snippets, tables, and structured data
        "select_paths": ["/workshop/.*", "/learn/.*", "/recipes/.*"],
        "exclude_paths": ["/de/.*", "/blog/.*", "/intro/showcase.*"],
        "instructions": (
            "Strudel syntax, functions, audio effects, samples, synths, "
            "mini-notation and MIDI/OSC reference and tutorial documentation"
        ),
    })

    # all_docs = res["results"]
    # metadata["source"] is the whole point: it survives chunking and ends up in
    # the retrieved Document, which is how the UI can cite the page it came from.
    # Pages with no extractable content are skipped rather than indexed empty.
    all_docs = [
        Document(page_content=result["raw_content"], metadata={"source": result["url"]})
        for result in res["results"]
        if result.get("raw_content")
    ]
    # all_docs contains the crawled documents, each represented as a Document object with its content and source URL.

    log_success(
        f"TavilyCrawl: Successfully crawled {len(all_docs)} documents from the documentation site.",
    )

    # Split documents into chunks
    log_header("DOCUMENT CHUNKING PHASE")
    log_info(f"Text Splitter: Processing {len(all_docs)} documents with 4000 chunk size and 200 overlap.", color=Colors.PURPLE)

    # "Recursive" = try to split on paragraph breaks first, then lines, then
    # words, then characters - so code blocks and sections stay intact where
    # possible. Always prefer it over CharacterTextSplitter for real documents.
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=4000,
        chunk_overlap=200   # carry 200 chars across the cut to preserve context
    )
    splitted_docs = text_splitter.split_documents(all_docs)
    log_success(f"Text Splitter: Successfully split {len(all_docs)} documents into {len(splitted_docs)} chunks.")

    # Second, independent source: the JSDoc-documented function reference
    # (lpf, gain, euclid, ...) pulled straight from the Strudel source repo.
    # Each function is already a single, self-contained unit of meaning, so
    # unlike the crawled prose above it is NOT run through the text splitter.
    log_header("API REFERENCE EXTRACTION PHASE")
    reference_docs = await fetch_reference_docs()
    log_success(f"JSDoc extraction: Found {len(reference_docs)} documented functions in packages/.")

    all_chunks = splitted_docs + reference_docs

    # Deterministic ids (hash of source + content) so re-running ingestion on
    # unchanged pages/functions UPDATES the same Pinecone vectors instead of
    # duplicating them; only chunks whose text actually changed get a new id.
    chunk_ids = [_chunk_id(doc) for doc in all_chunks]

    # Dumped to disk so core.py can build a BM25 (lexical) retriever without
    # re-crawling: hybrid BM25 + vector search catches exact function/keyword
    # matches ("lpf", "gain") that dense embeddings alone sometimes miss.
    _save_chunks(all_chunks, chunk_ids)

    # Process documents in batches asynchronously
    # Batched + concurrent, otherwise indexing thousands of chunks one HTTP call
    # at a time takes hours.
    await index_documents_async(all_chunks, chunk_ids, batch_size=500) # depending on the size of the documents, you may want to adjust the batch size for optimal performance.

    log_header("PIPELINE COMPLETE")
    log_success("🎉 Documentation ingestion pipeline finished successfully!")
    log_info("Summary:", Colors.BOLD)
    log_info(f"   • Crawled pages: {len(all_docs)}")
    log_info(f"   • Crawled-page chunks: {len(splitted_docs)}")
    log_info(f"   • API reference functions: {len(reference_docs)}")
    log_info(f"   • Total chunks indexed: {len(all_chunks)}")




def _clean_jsdoc_lines(raw_block: str) -> List[str]:
    """Strip the leading `*`/whitespace that JSDoc convention puts on every
    line of a `/** ... */` block, leaving just the text content per line."""
    lines = []
    for line in raw_block.split("\n"):
        line = line.strip()
        if line.startswith("*"):
            line = line[1:]
        lines.append(line.strip())
    return lines


def _parse_jsdoc_block(raw_block: str) -> Optional[Dict[str, Any]]:
    """Parse one `/** ... */` body into name/description/tags/synonyms/params/
    examples. Returns None for blocks with no `@name` - those are file/section
    level doc comments, not documented public functions, and jsdoc-json (the
    tool the real strudel.cc reference panel is built with) skips them too.
    """
    lines = _clean_jsdoc_lines(raw_block)

    # Split into (tag, content_lines) segments; untagged leading lines are
    # the free-text description.
    segments: List[tuple] = []
    current_tag: Optional[str] = None
    current_lines: List[str] = []
    for line in lines:
        m = _JSDOC_TAG_LINE_RE.match(line)
        if m:
            segments.append((current_tag, current_lines))
            current_tag, first = m.group(1), m.group(2)
            current_lines = [first] if first else []
        else:
            current_lines.append(line)
    segments.append((current_tag, current_lines))

    name = None
    description_lines: List[str] = []
    tags: List[str] = []
    synonyms: List[str] = []
    params: List[str] = []
    examples: List[str] = []

    for tag, content_lines in segments:
        text = "\n".join(content_lines).strip()
        if tag is None:
            description_lines.append(text)
        elif tag == "name":
            name = text.split()[0] if text else None
        elif tag == "tags":
            tags = [t.strip() for t in text.split(",") if t.strip()]
        elif tag == "synonyms":
            synonyms = [t.strip() for t in text.split(",") if t.strip()]
        elif tag == "param":
            if text:
                params.append(text)
        elif tag == "example" and text:
            examples.append(text)
        # other tags (@returns, @noAutocomplete, ...) aren't needed for RAG content

    if not name:
        return None

    return {
        "name": name,
        "description": "\n".join(d for d in description_lines if d).strip(),
        "tags": tags,
        "synonyms": synonyms,
        "params": params,
        "examples": examples,
    }


def _reference_doc_to_document(path: str, entry: Dict[str, Any]) -> Document:
    """Render one parsed JSDoc entry into a Document formatted like the
    "Source:\\n\\nContent:" shape core.py's retrieve_context tool expects."""
    lines = [f"Function: {entry['name']}"]
    if entry["synonyms"]:
        lines.append(f"Synonyms: {', '.join(entry['synonyms'])}")
    if entry["tags"]:
        lines.append(f"Tags: {', '.join(entry['tags'])}")
    lines.append("")
    lines.append(entry["description"])
    if entry["params"]:
        lines.append("")
        lines.append("Parameters:")
        lines.extend(f"- {p}" for p in entry["params"])
    if entry["examples"]:
        lines.append("")
        lines.append("Examples:")
        lines.extend(entry["examples"])

    source_url = f"{CODEBERG_SRC_BASE}{path}"
    return Document(
        page_content="\n".join(lines).strip(),
        metadata={
            "source": source_url,
            "type": "api-reference",
            "name": entry["name"],
            "tags": entry["tags"],
        },
    )


async def _list_reference_source_paths(client: httpx.AsyncClient) -> List[str]:
    """List every packages/**/*.{mjs,js,jsx} path in the repo via the Codeberg
    (Forgejo) git-trees API - the same file set the real `jsdoc packages/ ...`
    build command in the repo's package.json scans."""
    branch_resp = await client.get(f"{CODEBERG_API_BASE}/repos/{STRUDEL_REPO}/branches/{STRUDEL_BRANCH}")
    branch_resp.raise_for_status()
    commit_sha = branch_resp.json()["commit"]["id"]

    tree_resp = await client.get(
        f"{CODEBERG_API_BASE}/repos/{STRUDEL_REPO}/git/trees/{commit_sha}",
        params={"recursive": "true", "per_page": 5000},
    )
    tree_resp.raise_for_status()
    tree = tree_resp.json()["tree"]

    return [
        entry["path"]
        for entry in tree
        if entry["type"] == "blob"
        and entry["path"].startswith("packages/")
        and entry["path"].endswith(REFERENCE_SOURCE_EXTENSIONS)
    ]


async def fetch_reference_docs() -> List[Document]:
    """Fetch every packages/**/*.mjs|js source file from the Strudel repo and
    extract its JSDoc-documented functions (see STRUDEL_REPO comment above for
    why this is needed at all: the site's own "API Reference" panel is built
    from these same comments but only exists baked into client-side JS).
    Network failures degrade gracefully to an empty list (logged as a
    warning) so a Codeberg outage doesn't block the whole ingestion run.
    """
    try:
        async with httpx.AsyncClient(timeout=20) as client:
            paths = await _list_reference_source_paths(client)
            log_info(f"JSDoc extraction: {len(paths)} source files to scan under packages/.")

            # Codeberg's raw-file endpoint rate-limits (429) well before 234
            # concurrent/rapid requests complete; keep concurrency modest and
            # retry with backoff (honoring Retry-After when present) instead
            # of dropping source files silently.
            semaphore = asyncio.Semaphore(3)

            async def fetch_one(path: str) -> Optional[str]:
                async with semaphore:
                    for attempt in range(6):
                        try:
                            resp = await client.get(CODEBERG_RAW_BASE + path)
                            if resp.status_code == 429:
                                retry_after = resp.headers.get("Retry-After")
                                wait = float(retry_after) if retry_after else min(2 ** attempt, 30)
                                # Without this, a long Retry-After (Codeberg can send 600s)
                                # looks indistinguishable from the script being frozen.
                                log_warning(f"JSDoc extraction: {path} rate-limited (429), waiting {wait:.0f}s before retry...")
                                await asyncio.sleep(wait)
                                continue
                            resp.raise_for_status()
                            return resp.text
                        except Exception as e:
                            if attempt == 5:
                                log_warning(f"JSDoc extraction: Failed to fetch {path}: {e}")
                                return None
                            await asyncio.sleep(min(2 ** attempt, 30))
                    log_warning(f"JSDoc extraction: Gave up on {path} after repeated 429s.")
                    return None

            contents = await asyncio.gather(*[fetch_one(p) for p in paths])
    except Exception as e:
        log_error(f"JSDoc extraction: Could not reach Codeberg, skipping API reference source. Error: {e}")
        return []

    documents: List[Document] = []
    for path, source in zip(paths, contents):
        if source is None:
            continue
        for match in _JSDOC_BLOCK_RE.finditer(source):
            entry = _parse_jsdoc_block(match.group(1))
            if entry:
                documents.append(_reference_doc_to_document(path, entry))

    return documents


def _chunk_id(doc: Document) -> str:
    """Content-addressed id: same source+text always hashes to the same id, so
    a re-run upserts (overwrites) the existing vector instead of adding a
    duplicate. A chunk whose text changed gets a new id, which is the
    intended/acceptable tradeoff of this simple scheme (the stale vector under
    the old id is left orphaned in the index rather than explicitly deleted).
    """
    source = doc.metadata.get("source", "unknown")
    return hashlib.sha256(f"{source}::{doc.page_content}".encode("utf-8")).hexdigest()


def _save_chunks(documents: List[Document], ids: List[str]) -> None:
    """Persist the split chunks (content + metadata + id) to data/chunks.json."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    payload = [
        {"id": doc_id, "page_content": doc.page_content, "metadata": doc.metadata}
        for doc, doc_id in zip(documents, ids)
    ]
    CHUNKS_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    log_success(f"Chunk dump: Saved {len(payload)} chunks to {CHUNKS_PATH} (used by core.py for BM25 retrieval).")


async def index_documents_async(documents: List[Document], ids: List[str], batch_size: int = 50) -> None:
    """Process documents in batches asynchronously"""
    log_header("VECTOR STORAGE PHASE")
    log_info(
        f"VectorStore Indexing: Preparing to add {len(documents)} dicuments to vector store",
        color=Colors.DARKCYAN
    )

    # Slice the corpus into fixed-size batches; each batch is one upsert request.
    # ids are sliced in lockstep so each chunk keeps the same id used in chunks.json.
    # Create bathces
    batches = [
        documents[i : i + batch_size] for i in range(0, len(documents), batch_size)
    ]
    id_batches = [
        ids[i : i + batch_size] for i in range(0, len(ids), batch_size)
    ]

    log_info(f"VectorStore Indexing: Split into {len(batches)} batches of size {batch_size} for processing.")

    # Cap concurrent upserts so a large corpus doesn't fire hundreds of batches
    # at the embeddings API at once and trip the provider's rate limit.
    semaphore = asyncio.Semaphore(5)

    # Process all batches concurrently (bounded by the semaphore above)
    async def add_batch(batch: List[Document], batch_ids: List[str], batch_number: int) -> None:
        async with semaphore:
            try:
                # aadd_documents = embed + upsert, awaited so the event loop can run
                # the other batches while this one waits on the network.
                # Explicit ids -> Pinecone upserts by id (update-in-place) instead
                # of always inserting a fresh vector with a random uuid.
                await vectorStore.aadd_documents(batch, ids=batch_ids)
                log_success(f"VectorStore Indexing: Successfully added batch {batch_number + 1}/{len(batches)} to vector store.")
            except Exception as e:
                log_error(f"VectorStore Indexing: Failed to add batch {batch_number + 1}/{len(batches)}. Error: {str(e)}")

    # return_exceptions=True -> one failing batch does not cancel the others;
    # failures come back as Exception objects and are counted below.
    tasks = [add_batch(batch, id_batches[i], i) for i, batch in enumerate(batches)]
    results = await asyncio.gather(*tasks, return_exceptions=True)

    # Count successful batches
    successful_batches = sum(1 for result in results if not isinstance(result, Exception))

    if successful_batches == len(batches):
        log_success(
            f"VectorStore Indexing: Successfully added all batches to vector store."
        )
    else:
        log_warning(
            f"VectorStore Indexing: Added {successful_batches}/{len(batches)} batches successfully. Some batches failed."
        )

if __name__ == "__main__":
    asyncio.run(main())